### ISSUE TITLE
Build fails on Windows as rm -rf is unix command

### ISSUE THREAD

**Issue by UppaJung** [mrpatiwi/ReactNativeTS#9]
Recommend using package rimraf package
    "rimraf": "^2.5.4",

Replace rm -rf with rimraf in prebuild.  Get rid of pre-install as typings should be empty.

**Comment by lopezjurip** [comment]
Good suggestion, I'll change that 

---

Patricio López Juri

https://lopezjuri.com/

On jue, 26 de ene. de 2017 at 02:48 Stuart Schechter

<
mailto:Stuart Schechter <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Recommend using package rimraf package

"rimraf": "^2.5.4",

Replace rm -rf with rimraf in prebuild. Get rid of pre-install as typings should be empty.

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly,
https://github.com/mrpatiwi/ReactNativeTS/issues/9
, or

**Comment by nozzlegear** [comment]
I'm also running into this problem on Windows:

![image](https://cloud.githubusercontent.com/assets/2417276/25881362/2120ef68-3502-11e7-81ae-6aa054994992.png)

Fixed it by replacing `"prebuild": "node node_modules/.bin/rimraf build"` script with `"prebuild": "rimraf build"` in the package.json.
